### PR TITLE
Python 3.5.3 is required

### PR DESCRIPTION
**Pull request by eventh**
TravisCI tests failing as python 3.5.3 is required

### CODE REVIEW

**Comment by webknjaz** [comment]
Ref: travis-ci/travis-ci#9815

**Comment by eventh** [comment]
I saw, removed py3.7 and squashed the commits.

**Comment by webknjaz** [comment]
I suggest that you don't remove `3.7`, but add it to `allowed_failures:` list.

**Comment by webknjaz** [comment]
And please upvote that request in Travis's issues.

**Comment by eventh** [comment]
All done :)

**Pull request closed without merging**
